# Generated by Django 3.2.8 on 2022-10-20 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrival_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_city', models.CharField(choices=[('Almaty', 'ALMATY'), ('ASTANA', 'ASTANA'), ('KOKSHETAU', 'KOKSHETAU'), ('AKTAU', 'AKTAU'), ('ATYRAU', 'ATYRAU'), ('ORAL', 'ORAL'), ('SHYMKENT', 'SHYMKENT')], max_length=255, verbose_name='Город прилета')),
            ],
            options={
                'verbose_name': 'Arrival_city',
                'verbose_name_plural': 'Arrival_citys',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Departure_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_city', models.CharField(choices=[('Almaty', 'ALMATY'), ('ASTANA', 'ASTANA'), ('KOKSHETAU', 'KOKSHETAU'), ('AKTAU', 'AKTAU'), ('ATYRAU', 'ATYRAU'), ('ORAL', 'ORAL'), ('SHYMKENT', 'SHYMKENT')], max_length=255, verbose_name='Город вылета')),
            ],
            options={
                'verbose_name': 'Departure_city',
                'verbose_name_plural': 'Departure_citys',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=100, verbose_name='Номер рейса')),
                ('aircraft_type', models.CharField(max_length=50, verbose_name='Тип самолета')),
                ('time', models.TimeField(max_length=50, verbose_name='Время')),
                ('actual_time', models.TimeField(max_length=50, verbose_name='Фактическое время')),
                ('status', models.CharField(choices=[('FLEW_OUT', 'FLEW_OUT'), ('LANDED', 'LANDED'), ('LANDING', 'LANDING'), ('DETAIND', 'DETAIND')], max_length=50, verbose_name='Статус')),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.arrival_city')),
                ('departures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.departure_city')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'ordering': ('id',),
            },
        ),
    ]
