# Generated by Django 3.2.8 on 2022-10-25 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departures', models.CharField(max_length=150, verbose_name='Город вылета')),
                ('arrival', models.CharField(max_length=150, verbose_name='Город прилета')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Citys',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=100, verbose_name='Номер рейса')),
                ('aircraft_type', models.CharField(max_length=50, verbose_name='Тип самолета')),
                ('time', models.DateTimeField(max_length=50, verbose_name='Время')),
                ('actual_time', models.DateTimeField(max_length=50, verbose_name='Фактическое время')),
                ('status', models.CharField(choices=[('FLEW_OUT', 'FLEW_OUT'), ('LANDED', 'LANDED'), ('LANDING', 'LANDING'), ('DETAIND', 'DETAIND')], max_length=50, verbose_name='Статус')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.city', verbose_name='Город вылета')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'ordering': ('id',),
            },
        ),
    ]
