# Generated by Django 3.2.8 on 2022-10-20 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.arrival_city', verbose_name='Город прилета'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departures',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.departure_city', verbose_name='Город вылета'),
        ),
    ]
