# Generated by Django 3.2.8 on 2022-10-25 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_alter_flight_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.city', verbose_name='Город'),
        ),
    ]
